In [1]:
from scipy import stats
import numpy as np
import scipy.integrate as integrate
import matplotlib.pyplot as plt
from matplotlib import colors
from IPython.display import Image

# Getting familiarised with matrix operations

In [11]:
M=np.array( ((1,2),(3,4)) )
N=np.array( ((1.1,1.2),(1.3,1.4)) )
P=np.array( ((1j, 0), (2j, 4j)))

print(M)
print(N)
print(P)

[[1 2]
 [3 4]]
[[1.1 1.2]
 [1.3 1.4]]
[[0.+1.j 0.+0.j]
 [0.+2.j 0.+4.j]]


In [6]:
np.ones((3, 4)) * np.nan

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

## transpose

In [3]:
M.T

array([[1, 3],
       [2, 4]])

## conjugate transpose

In [9]:
np.matrix(M).getH()

matrix([[1, 3],
        [2, 4]])

In [12]:
np.matrix(P).getH()

matrix([[0.-1.j, 0.-2.j],
        [0.-0.j, 0.-4.j]])

## sum

In [14]:
M.sum(axis=0)

array([4, 6])

In [15]:
M + N

array([[2.1, 3.2],
       [4.3, 5.4]])

## matrix product

In [16]:
M.dot(N)

array([[3.7, 4. ],
       [8.5, 9.2]])

## element-by-element (Hadamard) product

In [17]:
M * N

array([[1.1, 2.4],
       [3.9, 5.6]])

## inversion

In [19]:
np.linalg.inv(M)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## Cholesky decomposition: $~~~{\bf M}={\bf L}\cdot{\bf L}^\dagger$

In [40]:
np.linalg.cholesky(np.array([[2, 5], [1, 3]]))

array([[1.41421356, 0.        ],
       [0.70710678, 1.58113883]])

In [41]:
_ * _.T

array([[2. , 0. ],
       [0. , 2.5]])

## Exponentiation

In [20]:
np.exp(M)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

## Within-matrix operations

In [25]:
N.mean(axis=1)

array([1.15, 1.35])